#spring.application.name=EurekaServer
spring:
  application:
    name: EurekaServer

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
#    hostname: localhost
    prefer-ip-address: true