server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: compendium-client-service
          uri: lb://compendium-client-service
          predicates:
            - Path=/compendium/**
          filters:
            - RewritePath=/compendium/(.*), /api/v1/$1
            - PreserveHostHeader=true

  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer uri is expected, but it doesnt work inside container
          issuer-uri: http://localhost:8090/realms/microservice-realm
          # overriding address to fetch the keys from to one working inside container (set up with jenkinsfile)
#          jwk-set-uri: http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info