#spring.application.name=ApiGateway
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: compendium-client-service
          uri: lb://compendium-client-service
          predicates:
            - Path=/compendium/**
          filters:
            - RewritePath=/compendium/(.*), /api/v1/$1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info