version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HTTP_ADDRESS=0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - ./keycloak_backup.sql:/docker-entrypoint-initdb.d/keycloak_backup.sql
    entrypoint: [ "bash", "-c", "
          echo 'Restoring Keycloak database...';
          docker-entrypoint.sh postgres & sleep 5;
          psql -h localhost -U keycloak -d keycloak < /docker-entrypoint-initdb.d/keycloak_backup.sql;
          wait;
        " ]
