version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8082:8082"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8082
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\india\Microservice-App:/home/code

volumes:
  jenkins_home: