version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HTTP_ADDRESS=0.0.0.0
    depends_on:
      - postgres-keycloak

  postgres-keycloak:
    image: postgres:latest
    container_name: postgres-keycloak
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - ./keycloak_backup.sql:/docker-entrypoint-initdb.d/keycloak_backup.sql

  eureka-server-service:
    image: russiandancer123/eureka-server-service:latest
    container_name: eureka
    ports:
      - "8761:8761"

  api-gateway-service:
    image: russiandancer123/api-gateway-service:latest
    container_name: api-gateway
    ports:
      - "8080:8090"
    depends_on:
      - eureka-server-service

  compendium-client-service:
    image: russiandancer123/compendium-client-service:latest
    container_name: compendium-client
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server-service