version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HTTP_ADDRESS=0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - ./keycloak_backup.sql:/docker-entrypoint-initdb.d/keycloak_backup.sql
    entrypoint: [ "bash", "-c", "
          echo 'Restoring Keycloak database...';
          docker-entrypoint.sh postgres & sleep 5;
          psql -h localhost -U keycloak -d keycloak < /docker-entrypoint-initdb.d/keycloak_backup.sql;
          wait;
        " ]

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8082"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8082
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

#  eureka-server-service:
#    build: ./../EurekaServer
#    container_name: eureka
#    ports:
#      - "8761:8761"
#
#  api-gateway-service:
#    build: ./../ApiGateway
#    container_name: api-gateway
#    ports:
#      - "8080:8090"
#    depends_on:
#      - eureka-server-service
#
#  compendium-client-service:
#    build: ./../CompendiumClientService
#    container_name: compendium-client
#    ports:
#      - "8081:8081"
#    depends_on:
#      - eureka-server-service