version: '3.8'

services:
  jenkins:
    image: jenkins-with-maven
    container_name: jenkins
    privileged: true
    user: jenkins
    ports:
      - "8082:8082"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - JENKINS_OPTS=--httpPort=8082
    depends_on:
      - docker

  docker:
    image: docker:dind
    privileged: true
    ports:
      - "2375:2375"
      - "8080:8080"
      - "8090:8090"
      - "8761:8761" #debug
      - "8081:8081" #debug
    environment:
      - DOCKER_TLS_CERTDIR=
    command: [
      "--host=tcp://0.0.0.0:2375",
      "--host=unix:///var/run/docker.sock",
      "--tls=false"
    ]

volumes:
  jenkins_home: